language: node_js
node_js:
- 4
- 6
- 7
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
before_script:
- npm prune

# travis_retry will try up to 3 times to run the script, which usually helps
# with flaky saucelabs connections for the `test:browser:cloud` command
script: travis_retry npm run $COMMAND
after_success:
- if [[ $TRAVIS_BRANCH == 'master' ]]; npm run docs && npm run deploydocs; fi
- npm run semantic-release
env:
  matrix:
  - COMMAND=test:browser:cloud
  - COMMAND=test
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
