ui: tape
browsers:
  - name: chrome
    version: [36, 37, 39, 41]
  - name: firefox
    version: [31, latest]
  - name: safari
    version: [6, 7, 8]
  - name: iphone
    version: [7.0, 8.0, latest]
  - name: internet explorer
    version: [10, 11]
scripts:
  - './node_modules/pouchdb/dist/pouchdb.js'
  - './node_modules/pouchdb/dist/pouchdb.memory.js'
  - './dist/pouchdb-hoodie-api.js'
